Added custom messages according to https://ubcsailbot.atlassian.net/w…
UBCSailbot/custom_interfaces pull request #2
Opened 2023-04-15 01:18 UTC by colinli02

…iki/spaces/prjt22/pages/1764623016/SOFT+Integration+Planning#Custom-Messages on 2023-04-13 6:04 PM

### Description

- There is no open issue.
- Refer to items here for "Colin" https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/edit-v2/1798504659

### Verification

- Built in ROS (sailbot_workspace) and passed.
![image](https://user-images.githubusercontent.com/102767231/232176227-c82deca1-0a09-4616-9644-ac9deb2c3525.png)

2023-04-15 01:22 UTC, patrick-5546 requested changes, later dismissed
Please add autogenerated files/directories to a `.gitignore` file loll

2023-04-15 17:20 UTC, patrick-5546 reviewed
I think we should make this our working spec, to replace https://ubcsailbot.atlassian.net/wiki/spaces/prjt22/pages/1764623016/SOFT+Integration+Planning#Interfaces. This way we don't have to update the confluence page during development when we want to make a change to a msg. To do so, we should comment descriptions for fields that are not obvious: conventions, range, etc..
- `speed` and `NUM_WIND_SENSORS` are examples of fields that are obvious
- `direction_degrees` and `voltage` are examples of fields that are not obvious

@hhenry01 this is why I was thinking it would be good to have `Speed` and `Heading` helper messages: we would only have to write the conventions in one place, rather than every time it is used (GPS, Ship, Wind).

2023-04-15 17:26 UTC, patrick-5546 commented on msg/LatLon.msg
Let's put internal/helper msgs like `LatLon` in a subdirectory

2023-05-25 01:46 UTC, colinli02 commented on msg/LatLon.msg
Added helpermsg/ within msg e.g.:
```
msg/helpermsg/LatLon.msg
```

2023-05-25 02:35 UTC, colinli02 commented
Made changes today. See:
https://github.com/UBCSailbot/ros_msgs/tree/remotes/origin/user/colinli02/custom_messages

Verified by passing build.

2023-05-29 22:00 UTC, colinli02 commented
I dismissed an old review message about adding a .gitignore that was based on an old commit that has been rebased out of log. Had some auto-generated files from an initial creation of tutorial_interfaces (now ros_msgs). These files don't appear anymore so it's all good.

2023-05-30 13:17 UTC, hhenry01 approved these changes

2023-05-31 02:33 UTC, patrick-5546 reviewed
On the confluence page, I see that the comments about having field names that are caps are unresolved:

- @hhenry01 can we change them?
- @colinli02 please update the confluence page according to Henry's response

Also Colin before you merge in this PR, can you publish a new version of the confluence page with a version comment that contains a link to this PR or the PR number?

2023-05-31 02:35 UTC, patrick-5546 commented on msg/LPathStats.msg
Let's delete this file for now, we can create it once we know what the fields are

2023-05-31 02:36 UTC, patrick-5546 commented on srv/Example.srv
Let's delete the srv directory, it only contains an example file

2023-05-31 02:40 UTC, patrick-5546 commented on msg/Ship.msg
> +float32 heading
Shouldn't the speed an heading fields be type `helpermsg/Heading`?

2023-05-31 02:44 UTC, patrick-5546 commented on msg/helpermsg/Vector3.msg
I'm thinking this repository should only contain msgs that are used across ROS packages (interfaces). If they are used only in one package, it should be defined in its `msg/` directory. Also maybe we should rename this repository `interfaces`. @colinli02 can you create a discussion topic in next software wide meeting to talk about this?

2023-06-02 02:26 UTC, patrick-5546 commented on msg/helpermsg/Vector3.msg
@DFriend01

2023-06-02 02:26 UTC, colinli02 commented on msg/helpermsg/Vector3.msg
To-do for me
- [ ] Rename ros_msgs -> ros_interface

2023-06-02 15:32 UTC, patrick-5546 commented on msg/helpermsg/Vector3.msg
Can rename repository `interfaces` instead of `ros_interface`. Also, do you want to rename the repository? It would involve renaming this GitHub repository and updating `new_project.repos` and the workspace file in sailbot workspace accordingly similar to what you did you add the `ros_msgs` repo.

2023-06-06 03:58 UTC, patrick-5546 commented
Just discovered this repository: https://github.com/ros2/common_interfaces/tree/humble

It defines some commonly used messages, including
- sensors, including GPS
- geometry, including vectors
- std: int, float, etc.

It may be worth taking a look at what the ros library offers before create our own custom types

2023-06-06 05:31 UTC, patrick-5546 commented on msg/helpermsg/Heading.msg
Just realized that subdirectories of `msg/` and `srv` aren't supported: https://github.com/ros2/rosidl/issues/213.

This can be verified through the `ros interface show` command:
![image](https://github.com/UBCSailbot/custom_interfaces/assets/65756895/85c58a43-2e94-4c15-ae25-bd6aa65f1f44)

2023-06-06 06:56 UTC, patrick-5546 commented on msg/Path.msg
Can you rename this to `DesiredHeading.msg`

2023-06-06 07:00 UTC, patrick-5546 reviewed
More renaming

2023-06-06 07:00 UTC, patrick-5546 commented on msg/AIS.msg
Rename to AISShips.msg

2023-06-06 07:00 UTC, patrick-5546 commented on msg/Ship.msg
Rename to AISShip.msg

2023-06-06 07:00 UTC, patrick-5546 commented on msg/Wind.msg
Rename to WindSensors.msg

2023-06-06 07:01 UTC, patrick-5546 commented on msg/helpermsg/Heading.msg
You can also try to find standard library msgs instead of defining our own helper messages: https://github.com/UBCSailbot/custom_interfaces/pull/2#issuecomment-1577866615

2023-06-13 23:21 UTC, colinli02 commented on msg/Wind.msg
Renamed

2023-06-13 23:21 UTC, colinli02 commented on msg/Ship.msg
Renamed

2023-06-13 23:22 UTC, colinli02 commented on msg/AIS.msg
Renamed

2023-06-13 23:23 UTC, colinli02 commented on msg/Path.msg
re-named

2023-06-13 23:42 UTC, colinli02 commented
Future to-do:
- [ ] Look at existing libraries https://github.com/UBCSailbot/custom_interfaces/pull/2#issuecomment-1577866615

2023-06-13 23:42 UTC, colinli02 commented
Also super weird, I don't know what's causing this but I noticed this last time and this time, ```ship.msg``` must exist or else ```custom_interfaces``` will not build. See error message:
```Executing task in folder sailbot_workspace: ./build.sh 

Starting >>> custom_interfaces
Starting >>> network_systems
Finished <<< network_systems [0.16s]                                                                  
--- stderr: custom_interfaces                            
In file included from /workspaces/sailbot_workspace/build/custom_interfaces/rosidl_generator_c/custom_interfaces/msg/detail/ais_ships__functions.h:19,
                 from /workspaces/sailbot_workspace/build/custom_interfaces/rosidl_generator_c/custom_interfaces/msg/detail/ais_ships__functions.c:4:
/workspaces/sailbot_workspace/build/custom_interfaces/rosidl_generator_c/custom_interfaces/msg/detail/ais_ships__struct.h:22:10: fatal error: custom_interfaces/msg/detail/ship__struct.h: No such file or directory
   22 | #include "custom_interfaces/msg/detail/ship__struct.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/custom_interfaces__rosidl_generator_c.dir/build.make:231: CMakeFiles/custom_interfaces__rosidl_generator_c.dir/rosidl_generator_c/custom_interfaces/msg/detail/ais_ships__functions.c.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:213: CMakeFiles/custom_interfaces__rosidl_generator_c.dir/all] Error 2
gmake[1]: *** Waiting for unfinished jobs....
In file included from /workspaces/sailbot_workspace/build/custom_interfaces/rosidl_typesupport_cpp/custom_interfaces/msg/ais_ships__type_support.cpp:7:
/workspaces/sailbot_workspace/build/custom_interfaces/rosidl_generator_cpp/custom_interfaces/msg/detail/ais_ships__struct.hpp:20:10: fatal error: custom_interfaces/msg/detail/ship__struct.hpp: No such file or directory
   20 | #include "custom_interfaces/msg/detail/ship__struct.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /workspaces/sailbot_workspace/build/custom_interfaces/rosidl_typesupport_fastrtps_cpp/custom_interfaces/msg/detail/ais_ships__rosidl_typesupport_fastrtps_cpp.hpp:11,
                 from /workspaces/sailbot_workspace/build/custom_interfaces/rosidl_typesupport_fastrtps_cpp/custom_interfaces/msg/detail/dds_fastrtps/ais_ships__type_support.cpp:4:
/workspaces/sailbot_workspace/build/custom_interfaces/rosidl_generator_cpp/custom_interfaces/msg/detail/ais_ships__struct.hpp:20:10: fatal error: custom_interfaces/msg/detail/ship__struct.hpp: No such file or directory
   20 | #include "custom_interfaces/msg/detail/ship__struct.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/custom_interfaces__rosidl_typesupport_cpp.dir/build.make:128: CMakeFiles/custom_interfaces__rosidl_typesupport_cpp.dir/rosidl_typesupport_cpp/custom_interfaces/msg/ais_ships__type_support.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:395: CMakeFiles/custom_interfaces__rosidl_typesupport_cpp.dir/all] Error 2
gmake[2]: *** [CMakeFiles/custom_interfaces__rosidl_typesupport_fastrtps_cpp.dir/build.make:154: CMakeFiles/custom_interfaces__rosidl_typesupport_fastrtps_cpp.dir/rosidl_typesupport_fastrtps_cpp/custom_interfaces/msg/detail/dds_fastrtps/ais_ships__type_support.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
In file included from /workspaces/sailbot_workspace/build/custom_interfaces/rosidl_typesupport_introspection_cpp/custom_interfaces/msg/detail/ais_ships__type_support.cpp:12:
/workspaces/sailbot_workspace/build/custom_interfaces/rosidl_generator_cpp/custom_interfaces/msg/detail/ais_ships__struct.hpp:20:10: fatal error: custom_interfaces/msg/detail/ship__struct.hpp: No such file or directory
   20 | #include "custom_interfaces/msg/detail/ship__struct.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [CMakeFiles/custom_interfaces__rosidl_typesupport_introspection_cpp.dir/build.make:154: CMakeFiles/custom_interfaces__rosidl_typesupport_introspection_cpp.dir/rosidl_typesupport_introspection_cpp/custom_interfaces/msg/detail/ais_ships__type_support.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:369: CMakeFiles/custom_interfaces__rosidl_typesupport_introspection_cpp.dir/all] Error 2
gmake[1]: *** [CMakeFiles/Makefile2:343: CMakeFiles/custom_interfaces__rosidl_typesupport_fastrtps_cpp.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< custom_interfaces [1.36s, exited with code 2]

Summary: 1 package finished [1.62s]
  1 package failed: custom_interfaces
  1 package had stderr output: custom_interfaces
  ```
  
  Resolved by making an empty "Ship.msg". Why?

2023-06-13 23:52 UTC, colinli02 commented on msg/helpermsg/Heading.msg
I've moved from ```helpermsg/``` to ```msg/``` . For some reason that command doesnt work (ros2 interface show custom_interfaces/)
![image](https://github.com/UBCSailbot/custom_interfaces/assets/102767231/a09d1c9c-4f5f-412b-a20b-93e41f135535)

So i manually verified using ```ros2 interface show <msg_type>```
![image](https://github.com/UBCSailbot/custom_interfaces/assets/102767231/2d1436d3-5b4f-4aa4-b8bd-35152c065c9c)

2023-06-13 23:54 UTC, colinli02 commented on srv/Example.srv
/srv deleted

2023-06-13 23:54 UTC, colinli02 commented on msg/LPathStats.msg
Deleted

2023-06-14 00:04 UTC, colinli02 commented on msg/Ship.msg
> +float32 heading
Fixed all to be helper msg type e.g.
```
LatLon lat_lon
Speed speed
Heading heading
```

2023-06-14 15:26 UTC, patrick-5546 commented on msg/helpermsg/Heading.msg
That wasn't a command, it was autocomplete (press tab)

2023-06-14 15:28 UTC, patrick-5546 commented on msg/helpermsg/Heading.msg
I think it would still be good to have some way to distinguish interfaces and their helpers if possible, here are my initial thoughts:

1. ~Do msgs have to be capitalized? What if we make interfaces uppercase and helpers lowercase?~ Not too sure about this, looking around I don't see anywhere where people have made lowercase messages. In fact, that may be confusing: https://answers.ros.org/question/328729/ros-msg-definitions-difference-between-std_msgstype-and-type/?answer=328730#post-id-328730

2. Prefix interfaces with `Inter`? And/or prefix helpers with `Helper`?

2023-06-14 15:36 UTC, patrick-5546 reviewed
Some more to dos:
- [x] Verify with @DFriend01 which msgs are internal to boat simulator and delete those (or create PR in boat_simulator to add those)
**Notes: Confirmed that ```Vector3``` and ```Kinematics``` are internal to boat simulator** - CL
- [x] Add comment to describe every field that isn't a custom message (e.g., `uint8`, `int32`)
- [x] Think of ways to distinguish interface and helper msgs and discuss with @patrick-5546 
**(Edit discussion 2023-06-16: Prefix ```Helper``` only, rest don't change) - CL**

- [ ] Add to README the name, publishers, and subscribers of each interface/topic
- [ ] After PR is merged, create PR in sailbot workspace to switch custom_interfaces branch/version to `main` in `src/new_project.repos`

2023-06-27 06:04 UTC, patrick-5546 approved these changes
Great work on this PR

2023-06-27 16:15 UTC, merged